@host=http://localhost:5036
@adminId=9bcc0302-9381-480f-ae9c-78bf75d3ca58

POST {{host}}/Subscriptions
Content-Type: application/json

{
    "SubscriptionType": "Free", // "Starter", "Pro"
    "AdminId": "{{adminId}}"
}

###

GET {{host}}/Subscriptions

//response
# {
#     "Id": ""
#     "SubscriptionType": "Free" // "Starter", "Pro"
# }