@host=http://localhost:5036
@adminId=3fa85f64-5717-4562-b3fc-2c963f66afa6

POST {{host}}/Subscriptions
Content-Type: application/json

{
    "SubscriptionType": "Free",
    "AdminId": "{{adminId}}"
}

###

GET {{host}}/Subscriptions/c4b86d59-7c5e-4d55-a3ad-e4021606c72a
